services:

  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=katalog
    volumes:
      - db-data:/var/lib/mysql
        #-./conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  front:
    container_name: front
    image: node:lts-bookworm  
    restart: always

    working_dir: /front
    entrypoint: ["npm", "run", "dev", "--", "-o", "--host", "0.0.0.0"]
    #  mount the volumes so we can change code and hot reload
    volumes:
      - './front:/front'
    #  port allows the host machine to link to container
    #  8000 for vue ui, 5000 for our vue app
    ports:
      - "3000:3000"
    depends_on:
      - connector

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  connector:
    build: ./connector
    container_name: connector
    tty: true
    stdin_open: true
    working_dir: /pg
    volumes:
      - ./connector:/pg
    entrypoint: ["flask", "run", "--debug", "--host=0.0.0.0"]
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx config
    depends_on:
      - front
      - connector

#  node:
#    image: node:lts-bookworm
#    tty: true
#    stdin_open: true
#    working_dir: /pg
#    volumes:
#      - ./node:/pg

volumes:
  db-data:
