# Localhost HTTP server for kolekcje
server {
	listen [::1]:80;
	server_name localhost;
	root /kolekcje/front/.output/public;
	index index.html;
	include kolekcje-locations.conf;
}

# HTTP to HTTPS redirect for kolekcje
server {
	listen 80;
	server_name kolekcje.lan;
	return 301 https://$host$request_uri;
}

# HTTPS server for kolekcje
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	include ssl.conf;
	root /kolekcje/front/.output/public;
	index index.html;
	server_name kolekcje.lan;
	include kolekcje-locations.conf;
}
